# <center>NUMPY ADVANCE</center>


# NUMPY RANDOM

## GENERATE RANDOM NUMBER

> Use randint() and module random in library numpy
>
> Example:
>
> Generate a random integer from 0 to 100:
>

In [1]:
from numpy import random

x = random.randint(100)

print(x)

#The random module's rand() method returns a random float between 0 and 1.

y = random.rand()

print(y)

93
0.5668369802997216


## GENERATE RANDOM ARRAY

> Use randint and attribute size
>

In [ ]:
x=random.randint(100, size=(5))

print(x)

#Or generate array 2-D
y = random.randint(100, size=(2, 4,1))

print(y)
#Or generate array have float
z = random.rand(5)
t = random.rand(2, 3)

print(z)
print(t)

## RANDOM NUMBER FROM AN ARRAY
 
> Use choie()
> 

In [11]:
x = random.choice([3, 5, 7, 9])

print(x)

#or add parameter size => generate new array from ele in an array
y = random.choice([3, 5, 7, 9], size=(3, 5))

print(y)

7
[[9 3 3 9 5]
 [7 3 7 5 9]
 [5 9 3 7 7]]


## DATA DISTRIBUTION

Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

## RANDOM DISTRIBUTION
>
>Example: generate a random array with frequency of element appear
>

In [3]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(len(x))
print(x)

100
[5 7 3 5 7 7 5 7 3 3 7 5 5 7 7 7 3 3 7 3 7 7 5 7 5 7 7 7 5 3 7 7 5 7 7 7 5
 7 7 3 7 7 7 7 7 7 7 7 7 5 7 5 7 7 7 7 7 5 5 5 5 7 7 7 7 5 7 7 7 5 5 7 5 7
 5 7 7 7 7 7 7 7 7 3 7 7 7 3 5 5 7 7 7 7 7 7 7 7 5 7]



## RANDOM PERMUTATIONS


A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation().

>
> Shuffling Arrays
> Shuffle means changing arrangement of elements in-place. i.e. in the array itself => random
>
> Example:

In [5]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[4 2 1 3 5]


> use permutation(): generate a random permutation of elements of following array:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

## SEABORN

Visualize Distributions With Seaborn

Seaborn is a library that uses Matplotlib underneath to plot graphs. It will be used to visualize random distributions.

## DISPLOT

> Plotting a displot
>
> Example:
>

import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot([0, 1, 2, 3, 4, 5])

plt.show()

## DISTRIBUTION RANDOM

1. NORMAL DISTRIBUTION
2. BINOMIAL DISTRIBUTION
3. POISSON DISTRIBUTION
4. UNIFORM DISTRIBUTION
5. LOGISTIC DISTRIBUTION
6. MULTINOMIAL DISTRIBUTION
7. EXPONENTIAL DISTRIBUTION
8. CHI SQUARE DISTRIBUTION
9. RAYLEIGH DISTRIBUTION
10. PARETO DISTRIBUTION
11. ZIPF DISTRIBUTION


### NORMAL DISTRIBUTION

The Normal Distribution is one of the most important distributions.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

Use the random.normal() method to get a Normal Data Distribution.

It has three parameters:

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array.


In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

sns.distplot(x, hist = False)


### BINOMIAL DISTRIBUTION

Binomial Distribution is a Discrete Distribution.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

It has three parameters:

n - number of trials.

p - probability of occurence of each trial (e.g. for toss of a coin 0.5 each).

size - The shape of the returned array.

> Example:
>

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot([1, 2, 3, 4, 6,7, 8, 9, 0], hist=True, kde=False)

plt.show()

**The main difference is that normal distribution is continous whereas binomial is discrete**


### POISSON DISTRIBUTION

Poisson Distribution is a Discrete Distribution.

It estimates how many times an event can happen in a specified time. e.g. If someone eats twice a day what is the probability he will eat thrice?

It has two parameters:

lam - rate or known number of occurrences e.g. 2 for above problem.

size - The shape of the returned array.

In [ ]:
from numpy import random

x = random.poisson(lam=3, size=10)

sns.distplot(random.poisson(lam=2, size=100), kde=False)

plt.show()
print(x)


### UNIFORM DISTRIBUTION

Used to describe probability where every event has equal chances of occuring.

E.g. Generation of random numbers.

It has three parameters:

a - lower bound - default 0 .0.

b - upper bound - default 1.0.

size - The shape of the returned array.



In [ ]:
sns.distplot(random.uniform(size=1000), hist=False)

plt.show()


### LOGISTIC DISTRIBUTION

Logistic Distribution is used to describe growth.

Used extensively in machine learning in logistic regression, neural networks etc.

It has three parameters:

loc - mean, where the peak is. Default 0.

scale - standard deviation, the flatness of distribution. Default 1.

size - The shape of the returned array.

In [ ]:
sns.distplot(random.logistic(size=1000), hist=False)

plt.show()


## NUMPY UFUNC

ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object

### CREATE YOUR OWN UFUNC

To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

1. function - the name of the function.
2. inputs - the number of input arguments (arrays).
3. outputs - the number of output arrays.

In [17]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))
print(type(np.add))

[6 8 10 12]
<class 'numpy.ufunc'>


### UFUNC SIMPLE ARITHMETIC
1. **Addition: np.add(np1, np2)**
2. **Subtraction: np.subtract(np1, np2)**
3. **Multiplication: np.multiply(np1, np2)**
4. **Division: np.divide(np1,np2)**
5. **Remaider: np.mod(np1, np2)**
6. **Quotient and remainder:np.divmod(np1, np2)**
7. **Absolute values: np.absolute(np1)**

In [19]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)
print(type(newarr))

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))
<class 'tuple'>
