
# <center>Learn Numpy in Python </center>



## Introduction

>Numpy is a library in Python.<br>
>It process array.



## Concepts



## Import Numpy:

> import numpy
>
> Example:
>
> import numpy
>
> arr = numpy.array([1, 2, 3, 4, 5])
>
> print(arr)



In [4]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


> or as np
>
> import numpy as np
>
> check version of numpy

In [5]:
print(numpy.__version__)

1.24.3



## CREATING A ARRAY IN NUMPY


In [7]:
import numpy as np
arr = np.array([1, 2])

0-D arrays: value is an value in array

In [8]:
arr = np.array(42)
print(arr)

42


1-D arrays:

In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2-D arrays:

In [11]:
arr = np.array([[1, 2, 3], [1, 2, 5]])
print(arr)

[[1 2 3]
 [1 2 5]]


use **ndim** check number n-D:

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Can define **ndim** when creat array:

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5



## NUMPY ARRAY INDEXING


HOW ACESS A ELEMENT IN ARRAY NUMPY:



In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


FOR 2-D ARRAYS, 3-D ARRAYS:

In [17]:
#2-D ARRAYS
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print(arr[1, 1])

#3-D ARRAYS
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 2])

2nd element on 1st row:  2
7
12


**Explain**:


> 3-D arrays have lot 2-D arrays and 2-D arrays also have lot 1-D arrays
>
> Index first use to chose 2-D arrays
>
> Index second use to chose 1-D arrays
>
> Index third use to chose element in 1-D arrays

Can use negative indexing:

In [21]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -2])

# negative index begin of right to left in a array

Last element from 2nd dim:  9



## NUMPY ARRAY SLICING


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: <font color='red'>[start:end]</font>.

We can also define the step, like this: <font color='red'>[start:end:step]</font>.

> Example:
>

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#index 1 to index 5(not included)
print(arr[1:5])

#index 4 to end
print(arr[4:])

#begin to index 4(not included)
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]



## NUMPY DATA TYPES


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixe-d chunk of memory for other type ( void )

Use **dtype** to check data type of element in numpy array:

In [24]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


Creating array with a defined data type for element:

In [25]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


> Example:
>
> Create an array with data type 4 bytes integer:
>

In [26]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


CONVERT DATA TYPE:

Not convert direct when creating a array

Best way: copy a new array and use **astype()** 

**astype()** have parameters be what data type you want


In [27]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32



## NUMPY ARRAY COPY AND VIEW


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

EXAMPLE:

In [29]:
#use copy:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [30]:
#use view:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


CHECK A ARRAY OWN ITS DATA

Use **base**: return **None** if the array owns the data 

In [31]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]



## NUMPY ARRAY SHAPE

### GET SHAPE OF AN ARRAY

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

EXAMPLE:

The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [33]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


Create an array with 5 dimensions using **ndmin** using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [37]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr[0, 0])
print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]]]
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


> EXAMPLE:
>

In [40]:
arr = np.array([[[1, 2, 3], [1, 2, 4]], [[1, 6, 7], [1, 2, 9]], [[1, 6, 7], [1, 2, 9]]])

print(arr.shape)

(3, 2, 3)
