# <center>NUMPY ADVANCE</center>


# NUMPY RANDOM

## GENERATE RANDOM NUMBER

> Use randint() and module random in library numpy
>
> Example:
>
> Generate a random integer from 0 to 100:
>

In [4]:
from numpy import random

x = random.randint(100)

print(x)

#The random module's rand() method returns a random float between 0 and 1.

y = random.rand()

print(y)

70
0.9572243639925103


## GENERATE RANDOM ARRAY

> Use randint and attribute size
>

In [ ]:
x=random.randint(100, size=(5))

print(x)

#Or generate array 2-D
y = random.randint(100, size=(2, 4,1))

print(y)
#Or generate array have float
z = random.rand(5)
t = random.rand(2, 3)

print(z)
print(t)

## RANDOM NUMBER FROM AN ARRAY
 
> Use choie()
> 

In [11]:
x = random.choice([3, 5, 7, 9])

print(x)

#or add parameter size => generate new array from ele in an array
y = random.choice([3, 5, 7, 9], size=(3, 5))

print(y)

7
[[9 3 3 9 5]
 [7 3 7 5 9]
 [5 9 3 7 7]]
